//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAppWithImagesInMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web;

    public partial class student
    {
        public int id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "Name is Required")]
        public string name { get; set; }

        [DisplayName("Gender")]
        public string gender { get; set; }

        [DisplayName("Age")]
        public Nullable<int> age { get; set; }
        [DisplayName("Class")]
        [Required(ErrorMessage = "Class is Required")]
        public Nullable<int> standard { get; set; }
        [DisplayName("Image")]
        public string image_path { get; set; }
        public Nullable<bool> IsActive { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
