//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAppWithImagesInMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int id { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name is Required")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name is Required")]

        public string lastname { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is Required")]
        public string gender { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is Required")]
        public int age { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is Required")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail address")]
        public string email { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "User Name is Required")]
        public string username { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is Required")]
        public string password { get; set; }
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password is Required")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "Password not Match")]
        public string confirm_password { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
